'''
Q1. What is the `random` module used for?
Ans. It is used to generate pseudo-random numbers for games, simulations, testing, and sampling.
'''
# Example
import random
random.random()   # e.g. 0.372


'''
Q2. What does “pseudo-random” mean in Python?
Ans. It means the numbers look random, but are generated by a deterministic algorithm.
'''
# Example
# Same seed → same results
random.seed(1)
random.random()


'''
Q3. What is the difference between `random()` and `randint(a, b)`?
Ans. `random()` returns a float between 0.0 and 1.0, while `randint()` returns an integer in a given range.
'''
# Example
random.random()        # 0.0 ≤ x < 1.0
random.randint(1, 6)  # like rolling a dice


'''
Q4. How do `choice()`, `choices()`, and `sample()` differ?
Ans. `choice()` picks one item, `choices()` allows repetition, `sample()` does not.
'''
# Example
items = ["a", "b", "c"]
random.choice(items)        # one element
random.choices(items, k=2)  # may repeat
random.sample(items, 2)     # no repetition


'''
Q5. What does `shuffle()` do?
Ans. It randomly rearranges the elements of a list in-place.
'''
# Example
nums = [1, 2, 3, 4]
random.shuffle(nums)
# nums order changed


'''
Q6. What is `seed()` and why is it useful?
Ans. `seed()` fixes randomness so results can be reproduced.
'''
# Example
random.seed(42)
random.randint(1, 10)


'''
Q7. When should you NOT use the `random` module?
Ans. Do not use it for security or cryptography-related tasks.
'''
# Example
# Use `secrets` module for passwords or tokens


'''
Q8. What is the one-line rule to remember?
Ans. The `random` module is great for simulations and testing, but not for security.
'''
# Example (lock it 🔒)
# Non-secure randomness → random
# Secure randomness     → secrets
